version: "3.8"

services:
  nginx:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mysibsau
      - default

volumes:
  caddy_data:
  caddy_config: 

networks:
  mysibsau:
    external: true